/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Test Runner Used To Run Each Test Below=====*/
#define RUN_TEST(TestFunc, TestLineNum) \
{ \
  Unity.CurrentTestName = #TestFunc; \
  Unity.CurrentTestLineNumber = TestLineNum; \
  Unity.NumberOfTests++; \
  if (TEST_PROTECT()) \
  { \
      setUp(); \
      TestFunc(); \
  } \
  if (TEST_PROTECT()) \
  { \
    tearDown(); \
  } \
  UnityConcludeTest(); \
}

/*=======Automagically Detected Files To Include=====*/
#ifdef __WIN32__
#define UNITY_INCLUDE_SETUP_STUBS
#endif
#include "unity.h"
#ifndef UNITY_EXCLUDE_SETJMP_H
#include <setjmp.h>
#endif
#include <stdio.h>
#include "vfd.h"
#include "vfd_test.h"

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_InitFunction_dummy(void);
extern void test_vfd_write_special_character_Glocke(void);
extern void test_vfd_write_special_character_Auto(void);
extern void test_vfd_write_special_character_Kolben(void);
extern void test_vfd_write_word_for_decimal_0(void);
extern void test_vfd_write_word_for_decimal_3(void);
extern void test_vfd_write_word_for_decimal_9(void);
extern void test_vfd_write_word_for_blanking(void);
extern void test_vfd_write_word_for_position_0(void);
extern void test_vfd_write_word_for_position_1(void);
extern void test_vfd_write_word_for_position_2(void);
extern void test_vfd_write_word_for_position_3(void);
extern void test_vfd_write_word_for_position_4(void);
extern void test_vfd_write_word_for_position_5(void);
extern void test_vfd_write_word_for_position_6(void);


/*=======Suite Setup=====*/
static void suite_setup(void)
{
#if defined(UNITY_WEAK_ATTRIBUTE) || defined(UNITY_WEAK_PRAGMA)
  suiteSetUp();
#endif
}

/*=======Suite Teardown=====*/
static int suite_teardown(int num_failures)
{
#if defined(UNITY_WEAK_ATTRIBUTE) || defined(UNITY_WEAK_PRAGMA)
  return suiteTearDown(num_failures);
#else
  return num_failures;
#endif
}

/*=======Test Reset Option=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  setUp();
}


/*=======MAIN=====*/
int main(void)
{
  suite_setup();
  UnityBegin("Testvfd.c");
  RUN_TEST(test_InitFunction_dummy, 22);
  RUN_TEST(test_vfd_write_special_character_Glocke, 33);
  RUN_TEST(test_vfd_write_special_character_Auto, 44);
  RUN_TEST(test_vfd_write_special_character_Kolben, 56);
  RUN_TEST(test_vfd_write_word_for_decimal_0, 68);
  RUN_TEST(test_vfd_write_word_for_decimal_3, 80);
  RUN_TEST(test_vfd_write_word_for_decimal_9, 92);
  RUN_TEST(test_vfd_write_word_for_blanking, 103);
  RUN_TEST(test_vfd_write_word_for_position_0, 114);
  RUN_TEST(test_vfd_write_word_for_position_1, 123);
  RUN_TEST(test_vfd_write_word_for_position_2, 132);
  RUN_TEST(test_vfd_write_word_for_position_3, 141);
  RUN_TEST(test_vfd_write_word_for_position_4, 150);
  RUN_TEST(test_vfd_write_word_for_position_5, 159);
  RUN_TEST(test_vfd_write_word_for_position_6, 168);

  return suite_teardown(UnityEnd());
}
